version: '3.5'

services:
  instancer:
    build: .
    entrypoint: /www/docker-entrypoint.sh
    ports:
      - "80:80"
    privileged: true
    environment:
      - TITLE=AMF::Instancer
      - INSTANCER_HOST=sandbox.local
      - CHALL_BASE_HOST=.test.splitline.tw
      - SCOREBOARD_URL=http://35.201.208.240
      - AUTO_DESTROY=15 # minutes
